const NAME_SPACE = 'agileEngine';

export const GET_INITIAL_TEXT_REQUEST = `${NAME_SPACE}/GET_INITIAL_TEXT_REQUEST`;
export const GET_INITIAL_TEXT_SUCCESS = `${NAME_SPACE}/GET_INITIAL_TEXT_SUCCESS`;
export const GET_INITIAL_TEXT_ERROR = `${NAME_SPACE}/GET_INITIAL_TEXT_ERROR`;

export const GET_SYNONYMS_REQUEST = `${NAME_SPACE}/GET_SYNONYMS_REQUEST`;
export const GET_SYNONYMS_SUCCESS = `${NAME_SPACE}/GET_SYNONYMS_SUCCESS`;
export const GET_SYNONYMS_ERROR = `${NAME_SPACE}/GET_SYNONYMS_ERROR`;


export default {
  GET_INITIAL_TEXT_REQUEST,
  GET_INITIAL_TEXT_SUCCESS,
  GET_INITIAL_TEXT_ERROR,
  GET_SYNONYMS_REQUEST,
  GET_SYNONYMS_SUCCESS,
  GET_SYNONYMS_ERROR,
};
